### ISSUE TITLE
Issue with Spectre.Console.StyleParser.Parse

### ISSUE THREAD

**Issue by nt74** [Samsung-Loki/Syndical#11]
Command: 
`Syndical.Application -m Download -v A235FXXU4CWH1/A235FOXE4CWH1/A235FXXU4CWH7/A235FXXU4CWH1 -M SM-A235F -r SER -f`

Issue:
Exception occured: Could not find color or style 'yelloe'.

Logs:

> System.InvalidOperationException: Could not find color or style 'yelloe'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 20
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 26
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 41
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 62
   at Syndical.Application.Program.<>c__DisplayClass2_0.<Main>b__3(ProgressContext ctx)
   at Spectre.Console.Progress.<>c__DisplayClass25_0.<Start>b__0(ProgressContext ctx) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 70
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 103
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 138
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.Run[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 44
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 121
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 101
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 74
   at Syndical.Application.Program.<>c.<Main>b__2_0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Syndical.Application.Program.Main(String[] args)

**Comment by TheAirBlow** [comment]
LMAO HOW DID I MISS SUCH A SILLY TYPO

**Comment by TheAirBlow** [comment]
Was fixed long ago lol
